### PR TITLE
Fix parsing json on lookup without found row

### LINKED ISSUE #104: MobileServiceTable lookUp does not propagate exception thrown when row does not exist
Referencing [MobileServiceJsonTable.java Line 956](https://github.com/Azure/azure-mobile-apps-android-client/blob/master/sdk/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/MobileServiceJsonTable.java#L956)

- When a row for a given id does not exist, response is a string containing "null". 
- The JsonElement is parsed without exception and passed to [line 411](https://github.com/Azure/azure-mobile-apps-android-client/blob/master/sdk/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/MobileServiceJsonTable.java#L411) where results.first is a JsonElement, but not a JsonArray or a JsonObject. 
- The exception "java.lang.IllegalStateException: Not a JSON Object: null" is thrown, and never passed to the SettableFuture declared on [line 367](https://github.com/Azure/azure-mobile-apps-android-client/blob/master/sdk/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/MobileServiceJsonTable.java#L367). 
- Any callbacks added to this future never receive a success or failure.

### PR DESCRIPTION
**Pull request by MatkovIvan**
Fixes #104
Also fixed param names in the comments.

### CODE REVIEW

File: sdk/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/MobileServiceJsonTable.java [hunk 1]
```diff
@@ -403,7 +403,7 @@ public void onFailure(Throwable exc) {
 
             @Override
             public void onSuccess(Pair<JsonElement, ServiceFilterResponse> results) {
-                if (results.first.isJsonArray()) {
+                if (!results.first.isJsonObject()) {
```
Comment (dhei) [inline sdk/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/MobileServiceJsonTable.java]: This fix looks good. Can you add a unit test?

File: sdk/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/MobileServiceJsonTable.java [hunk 2]
```diff
@@ -880,7 +880,7 @@ public void onSuccess(JsonObject result) {
     /**
      * Executes the query against the table
      *
-     * @param request        Request to execute
+     * @param path           Request to execute
```
Comment (dhei) [inline sdk/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/MobileServiceJsonTable.java]: `Request to execute` looks confusing here, can you change to some wording coherent with "path"?
